/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"


void
rpc_1(char *host, int a, int b)
{
	CLIENT *clnt;
	struct outarg  *result_1;
	struct inarg  addition_1_arg;
        addition_1_arg.a=a;
	addition_1_arg.b=b;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC, factorial, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = addition_1(&addition_1_arg, clnt);
	if (result_1 == (struct outarg *) NULL) {
		clnt_perror (clnt, "call failed");
	}
printf("Sum is %d",result_1->out);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
rpc_2(char *host, int a,int b)
{
	CLIENT *clnt;
	struct outarg  *result_1;
	struct inarg  sub_2_arg;
sub_2_arg.a=a;
	sub_2_arg.b=b;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC, Sub, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sub_2(&sub_2_arg, clnt);
	if (result_1 == (struct outarg *) NULL) {
		clnt_perror (clnt, "call failed");
	}
printf("Diff is %d",result_1->out);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
rpc_3(char *host, char a[], char b[])
{
	CLIENT *clnt;
	struct stroutarg  *result_1;
	struct String_inarg  str_3_arg;
        strcpy(str_3_arg.a,a);
	strcpy(str_3_arg.b,b); 
#ifndef	DEBUG
	clnt = clnt_create (host, RPC, cat, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = str_3(&str_3_arg, clnt);
	if (result_1 == (struct stroutarg *) NULL) {
		clnt_perror (clnt, "call failed");
	}
printf("Concat op= %s\n",result_1->out);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
rpc_4(char *host, int a)
{
	CLIENT *clnt;
	struct outarg  *result_1;
	struct inarg  facto_4_arg;
        facto_4_arg.a=a;


#ifndef	DEBUG
	clnt = clnt_create (host, RPC, fact, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = facto_4(&facto_4_arg, clnt);
	if (result_1 == (struct outarg *) NULL) {
		clnt_perror (clnt, "call failed");
	}
printf("Fact op= %d\n",result_1->out);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
printf("1 Add 2 Sub 3 Concat 4 fact");
	int sw;
	scanf("%d",&sw);
	int a,b;
	char F[20],S[20];
		
switch(sw){	
	case 1:	printf("Enter numbers");
		scanf("%d %d",&a,&b);
		rpc_1 (host,a,b);
		break;
	case 2:	
		printf("Enter numbers");
		scanf("%d %d",&a,&b);
		rpc_2 (host,a,b);
		break;
	case 3:
		printf("Enter strings");
		scanf("%s %s",F,S);	
		rpc_3 (host,F,S);
                break;
        case 4:
		printf("Enter Number");
		scanf("%d",&a);	
		rpc_4 (host,a);
                

}
	/*rpc_1 (host);
	rpc_2 (host);
	rpc_3 (host);
	rpc_4 (host);*/
exit (0);
}
