/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

struct outarg *
addition_1_svc(struct inarg *argp, struct svc_req *rqstp)
{
	static struct outarg  result;

	/*
	 * insert server co
	 */
result.out=(argp->a)+(argp->b);

	return &result;
}

struct outarg *
sub_2_svc(struct inarg *argp, struct svc_req *rqstp)
{
	static struct outarg  result;

	/*
	 * insert server code here
	 */
result.out=argp->a-argp->b;

	return &result;
}

struct stroutarg *
str_3_svc(struct String_inarg *argp, struct svc_req *rqstp)
{
	static struct stroutarg  result;

	/*
	 * insert server code here
	 */
strcat(argp->a,argp->b);
	strcpy(result.out,argp->a);

	return &result;
}

struct outarg *
facto_4_svc(struct inarg *argp, struct svc_req *rqstp)
{
	static struct outarg  result;

	/*
	 * insert server code here
	 */
       result.out=1;
        int i;
	for(i=argp->a;i>0;i--)
	{
result.out=(result.out)*i;
	
}
return &result;
}
